### ISSUE TITLE
bug: `kcl mod add k8s` panic

### ISSUE THREAD

**Issue by zong-zhe** [kcl-lang/cli#28]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

<img width="724" alt="Screenshot 2023-12-22 at 11 56 01" src="https://github.com/kcl-lang/cli/assets/68977949/f75d7f90-2651-48c8-98ea-283ed20faa81">

### 2. What did you expect to see? (Required)

`kcl mod add k8s` should  add the dependency k8s:1.29 successfully.

### 3. What did you see instead (Required)

It panic.

### 4. What is your KCL components version? (Required)

The main branch of KCL CLI installed by `go install kcl-lang.io/cli/cmd/kcl@main`.

**Comment by Peefy** [comment]
Closed by https://github.com/kcl-lang/kpm/pull/239
